# Generated by Django 3.2 on 2021-04-09 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=260)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Powers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'powers',
            },
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'universos',
            },
        ),
        migrations.CreateModel(
            name='Powers_character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name=100)),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universos.character')),
                ('powers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universos.powers')),
            ],
            options={
                'db_table': 'powers_character',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universos.universe'),
        ),
    ]
